packages: []

catalog:
  '@primeuix/themes': ^1.2.5
  '@primevue/auto-import-resolver': ^4.4.1
  '@supabase/supabase-js': ^2.81.1
  '@tailwindcss/vite': ^4.1.17
  '@types/node': ^24.10.1
  '@unovis/ts': ^1.6.2
  '@unovis/vue': ^1.6.2
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  lucide-vue-next: ^0.548.0
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: ^0.7.1
  primevue: ^4.4.1
  reka-ui: ^2.6.0
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.17
  tw-animate-css: ^1.4.0
  vue-sonner: ^2.0.9

catalogs:
  build:
    '@intlify/unplugin-vue-i18n': ^6.0.8
    '@shikijs/markdown-it': ^3.15.0
    '@unocss/eslint-config': ^66.5.6
    '@vitejs/plugin-vue': ^5.2.4
    beasties: ^0.2.0
    markdown-it-link-attributes: ^4.0.1
    rollup: ^4.53.2
    shiki: ^3.15.0
    unocss: ^66.5.6
    unplugin: ^2.2.2
    unplugin-auto-import: ^19.3.0
    unplugin-vue-components: ^28.8.0
    unplugin-vue-macros: ^2.14.5
    unplugin-vue-markdown: ^28.3.1
    unplugin-vue-router: ^0.12.0
    vite: ^6.2.3
    vite-bundle-visualizer: ^1.2.1
    vite-plugin-inspect: ^11.0.0
    vite-plugin-pwa: ^0.21.2
    vite-plugin-vue-devtools: ^7.7.8
    vite-plugin-vue-layouts: ^0.11.0
    vite-ssg: ^26.1.1
    vite-ssg-sitemap: ^0.8.1
  dev:
    '@antfu/eslint-config': ^4.19.0
    '@iconify-json/carbon': ^1.2.14
    '@vue-macros/volar': ^3.1.1
    '@vue/test-utils': ^2.4.6
    cypress: ^14.5.4
    cypress-vite: ^1.8.0
    eslint: ^9.39.1
    eslint-plugin-cypress: ^4.3.0
    eslint-plugin-format: ^1.0.2
    https-localhost: ^4.7.1
    lint-staged: ^15.5.2
    simple-git-hooks: ^2.13.1
    taze: ^19.9.0
    typescript: ^5.9.3
    vitest: ^3.2.4
    vue-tsc: ^2.2.12
  frontend:
    '@nuxt/ui': ^4.1.0
    '@unhead/vue': ^2.0.19
    '@unocss/reset': ^66.5.6
    '@vueuse/core': ^13.9.0
    nprogress: ^0.2.0
    pinia: ^3.0.4
    vue: ^3.5.24
    vue-i18n: ^11.1.12
    vue-router: ^4.6.3
  types:
    '@types/markdown-it-link-attributes': ^3.0.5
    '@types/nprogress': ^0.2.3
  conflicts_build_h6_4_1:
    vite: ^6.4.1
  conflicts_build_h11_3_3:
    vite-plugin-inspect: ^11.3.3

onlyBuiltDependencies:
  - cypress
  - esbuild
  - simple-git-hooks
