/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/ui/button/Button.vue')['default']
    HomeNavbar: typeof import('./components/HomeNavbar.vue')['default']
    IndexFooter: typeof import('./components/IndexFooter.vue')['default']
    IndexNavbar: typeof import('./components/IndexNavbar.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/IndexFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
